spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer-management-service1
    username: app_user
    password: app_user_pwd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: customer
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true # Set to false to disable Liquibase
    change-log: classpath:db/changelog/changelog-master.xml
    default-schema: customer


